services:
  - type: web
    name: finance-app-backend
    env: node
    region: oregon
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npx prisma migrate deploy
    startCommand: |
      cd backend
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: finance-app-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MINDEE_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://finance-app-frontend.onrender.com

  - type: web
    name: finance-app-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://finance-app-backend.onrender.com

databases:
  - name: finance-app-db
    databaseName: finance_app
    user: finance_user
